module.exports = {
  env: {
    KOPO_ADDRESS_PROVIDER_LOCALHOST: process.env.KOPO_ADDRESS_PROVIDER_LOCALHOST,
    KOPO_ROLES_MANAGER_LOCALHOST: process.env.KOPO_ROLES_MANAGER_LOCALHOST,
    KOPO_DOCUMENT_HANDLER_LOCALHOST: process.env.KOPO_DOCUMENT_HANDLER_LOCALHOST,
    KOPO_FOLDER_FACTORY_LOCALHOST: process.env.KOPO_FOLDER_FACTORY_LOCALHOST,
    KOPO_ADDRESS_PROVIDER_MUMBAI: process.env.KOPO_ADDRESS_PROVIDER_MUMBAI,
    KOPO_ROLES_MANAGER_MUMBAI: process.env.KOPO_ROLES_MANAGER_MUMBAI,
    KOPO_DOCUMENT_HANDLER_MUMBAI: process.env.KOPO_DOCUMENT_HANDLER_MUMBAI,
    KOPO_FOLDER_FACTORY_MUMBAI: process.env.KOPO_FOLDER_FACTORY_MUMBAI,
  },
};
